In [ ]:
import numpy as np

In [ ]:
myList = [1, 4, 6, 2, "strings", [10, 20, 30]]
print(myList)

[1, 4, 6, 2, 'strings', [10, 20, 30]]


In [ ]:
myList.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [ ]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [ ]:
%timeit my_arr2 = my_arr * 2

471 µs ± 43.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit my_list2 = [x * 2 for x in my_list]

38 ms ± 8.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


NumPy operations perform complex computations on entire arrays without the need for Python for loops, which can be slow for large sequences. NumPy is faster than regular Python code because its C-based algorithms avoid overhead present with regular interpreted Python code

# The NumPy ndarray: A Multidimensional Array Object

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

In [ ]:
arr_1d = np.array([1, 3.0, 4, 5, 7.8, 9.2])
print(arr_1d)

[1.  3.  4.  5.  7.8 9.2]


In [ ]:
arr_1d.dtype

dtype('float64')

In [ ]:
arr_2d = np.array([[1.5, -0.1, 3], [0, -3, 6.5], [2.4, 0, 1], [0.7, 2, 5]])
print(arr_2d)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]
 [ 2.4  0.   1. ]
 [ 0.7  2.   5. ]]


In [ ]:
arr_2d * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.],
       [ 24.,   0.,  10.],
       [  7.,  20.,  50.]])

In [ ]:
arr_2d.shape

(4, 3)

In [ ]:
arr_2d.dtype

dtype('float64')

In [ ]:
arr_2d[:2]

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

### Creating ndarrays
The easiest way to create an array is to use the array function. This accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data. For example, a list is a good candidate for conversion:

In [ ]:
lst1 = [6, 7.5, 8, 0, 1]

In [ ]:
arr1 = np.array(lst1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

Unless explicitly specified, numpy.array tries to infer a good data type for the array that it creates. The data type is stored in a special dtype metadata object; for example, in the previous two examples we have:

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
my_arr = np.array([0, 1, 2, "Here is a very very very very long string of characters"])
print(my_arr.dtype)

<U55


In [ ]:
print(my_arr)

['0' '1' '2' 'Here is a very very very very long string of characters']


# 1.Different ways of initialization



### a. Intrinsic array creation functions

---



In [ ]:
# return evenly spaced values within a given interval
range_arr = np.arange(10)
print("An array given range is \n", range_arr, " with dimensions ", range_arr.shape, "\n")

# return evenly spaced numbers over a specified interval
linspace_arr = np.linspace(2.0, 3.0, num=5, endpoint=True)
print("An evenly spaced array given range is \n", linspace_arr, " with dimensions ", linspace_arr.shape, "\n")

An array given range is 
 [0 1 2 3 4 5 6 7 8 9]  with dimensions  (10,) 

An evenly spaced array given range is 
 [2.   2.25 2.5  2.75 3.  ]  with dimensions  (5,) 



In [ ]:
# initialize an empty array with size 2 x 2
empty_arr = np.empty((2, 2))
print("An empty array is \n", empty_arr, " with dimensions ", empty_arr.shape, "\n")

# initialize an all zero array with size 2 x 3
zeros_arr = np.zeros((2, 3))
print("A zeros array is \n", zeros_arr, " with dimensions ", zeros_arr.shape, "\n")

# initialize an all one array with size 4 x 2
ones_arr = np.ones((4, 2))
print("A ones array is \n", ones_arr, " with dimensions ", ones_arr.shape, "\n")

An empty array is 
 [[6.  7.5]
 [8.  1. ]]  with dimensions  (2, 2) 

A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimensions  (2, 3) 

A ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  with dimensions  (4, 2) 



In [ ]:
# return an array of zeros with the same shape and type as a given array
zeros_like_arr = np.zeros_like(ones_arr)
print("A zero like array is \n", zeros_like_arr, " with dimensions ", zeros_like_arr.shape, "\n")

# return an array of ones with the same shape and type as a given array
ones_like_arr = np.ones_like(zeros_arr)
print("A ones like array is \n", ones_like_arr, " with dimensions ", ones_like_arr.shape, "\n")

A zero like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]  with dimensions  (4, 2) 

A ones like array is 
 [[1. 1. 1.]
 [1. 1. 1.]]  with dimensions  (2, 3) 



### b. Create an array from existing data

Conversion from other python structures (i.e lists and tuples)

In [ ]:
# initialize an array with the given list
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, " with dimensions ", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4]  with dimensions  (4,) 



Reading arrays from disk

In [ ]:
# initialize an array by loading data from a txt file
txt_arr = np.loadtxt("/content/example_data.txt")

# initialize an array by loading data from a npy file
loaded_arr = np.load("/content/example_data.npy")

FileNotFoundError: /content/example_data.txt not found.

In [ ]:
print(txt_arr)

In [ ]:
print(loaded_arr)

The .npy file format is a binary format used by NumPy to store arrays efficiently.
The .npy file format stores array data in binary form, which is more compact and faster to read/write than plain text (e.g., .txt or .csv files). This allows for quick saving and loading of large arrays.

**Metadata Included:** The .npy format stores additional information about the array:

**Shape:** The dimensions of the array (e.g., 2x3).
Data type: The type of data stored in the array (e.g., int32, float64).

**Endianness:** Information about the byte order, ensuring compatibility across different systems.
This metadata helps NumPy reconstruct the array exactly as it was saved, without needing extra information from the user.

Use of special library functions (e.g., random)

In [ ]:
a = np.random.randint(0, 10, size = (1,4))
print("Random integer array", a, "of shape ", a.shape)

np.random.seed(0)
a = np.random.randint(0, 10, size = (1,4))
print("Random integer array with seed", a, "of shape ", a.shape)

Random integer array [[8 0 1 5]] of shape  (1, 4)
Random integer array with seed [[5 0 3 3]] of shape  (1, 4)


In [ ]:
# create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
uniform_rand_arr = np.random.rand(3,2)
print("A random array from a uniform distribution is \n", uniform_rand_arr, " with dimensions ", uniform_rand_arr.shape, "\n")

# For random samples from N(\mu, \sigma^2), use:
# sigma * np.random.randn(...) + mu
mu = 3
sigma =2.5
sample_normal_arr = mu + sigma * np.random.randn(2, 4)
print("A random array from a gaussian distribution is \n", sample_normal_arr)
print("with mu: ", mu)
print("with sigma: ", sigma)
print("with dimensions ", sample_normal_arr.shape)

A random array from a uniform distribution is 
 [[0.84725174 0.6235637 ]
 [0.38438171 0.29753461]
 [0.05671298 0.27265629]]  with dimensions  (3, 2) 

A random array from a gaussian distribution is 
 [[ 6.41366795  2.7557607  -3.06488643  1.8673605 ]
 [ 1.82307249  5.43253999 -0.19537279  6.5934267 ]]
with mu:  3
with sigma:  2.5
with dimensions  (2, 4)


# 2.Compound Data Types - Matrices (ndarrays)
Matrices can also be created and populated using list comprehension syntax. The example below creates a matrix of width 3 and height 4. All elements in the matrix are initially set to zero. This is effectively a list of lists.

In [ ]:
myMatrix = [[0 for x in range(3)] for y in range(4)]

print(myMatrix)

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [ ]:
myMatrix[0][0] = 5
myMatrix[1][1] = 6
myMatrix[2][2] = 2

print(myMatrix)

[[5, 0, 0], [0, 6, 0], [0, 0, 2], [0, 0, 0]]


# Accessing Data

### a. Indexing: Accessing values from Numpy Arrays

In [ ]:
n = np.random.rand(4,5,6) # see this as 4 batches, each containing 5 rows and 6 columns
n

array([[[0.95715516, 0.14035078, 0.87008726, 0.47360805, 0.80091075,
         0.52047748],
        [0.67887953, 0.72063265, 0.58201979, 0.53737323, 0.75861562,
         0.10590761],
        [0.47360042, 0.18633234, 0.73691818, 0.21655035, 0.13521817,
         0.32414101],
        [0.14967487, 0.22232139, 0.38648898, 0.90259848, 0.44994999,
         0.61306346],
        [0.90234858, 0.09928035, 0.96980907, 0.65314004, 0.17090959,
         0.35815217]],

       [[0.75068614, 0.60783067, 0.32504723, 0.03842543, 0.63427406,
         0.95894927],
        [0.65279032, 0.63505887, 0.99529957, 0.58185033, 0.41436859,
         0.4746975 ],
        [0.6235101 , 0.33800761, 0.67475232, 0.31720174, 0.77834548,
         0.94957105],
        [0.66252687, 0.01357164, 0.6228461 , 0.67365963, 0.971945  ,
         0.87819347],
        [0.50962438, 0.05571469, 0.45115921, 0.01998767, 0.44171092,
         0.97958673]],

       [[0.35944446, 0.48089353, 0.68866118, 0.88047589, 0.91823547,
         0.216822

In [ ]:
n.shape

(4, 5, 6)

In [ ]:
n.ndim

3

In [ ]:
n[0, 2, 3] # returns the element located in the fourth column of third row of the first batch.

np.float64(0.21655035442437187)

### b. Slicing: Accessing subsections of Numpy Arrays based on **Indices**

In [ ]:
# slice along a batch
print(n[0, :, :]) # same as: n[0]



# slice along multiple batches


[[0.95715516 0.14035078 0.87008726 0.47360805 0.80091075 0.52047748]
 [0.67887953 0.72063265 0.58201979 0.53737323 0.75861562 0.10590761]
 [0.47360042 0.18633234 0.73691818 0.21655035 0.13521817 0.32414101]
 [0.14967487 0.22232139 0.38648898 0.90259848 0.44994999 0.61306346]
 [0.90234858 0.09928035 0.96980907 0.65314004 0.17090959 0.35815217]]


In [ ]:
print(n[0, 0:3, 0:4])

[[0.95715516 0.14035078 0.87008726 0.47360805]
 [0.67887953 0.72063265 0.58201979 0.53737323]
 [0.47360042 0.18633234 0.73691818 0.21655035]]


In [ ]:
print(n[:, 3, 4]) # returns the elements in the 4th row and 5th column across all batches

[0.44994999 0.971945   0.14644176 0.38346223]


In [ ]:
#syntax for slicing at interval is start:stop:step_size

print(n[0::2]) # slices from index 0 to the end of the dimension at intervals of 2


[[[0.95715516 0.14035078 0.87008726 0.47360805 0.80091075 0.52047748]
  [0.67887953 0.72063265 0.58201979 0.53737323 0.75861562 0.10590761]
  [0.47360042 0.18633234 0.73691818 0.21655035 0.13521817 0.32414101]
  [0.14967487 0.22232139 0.38648898 0.90259848 0.44994999 0.61306346]
  [0.90234858 0.09928035 0.96980907 0.65314004 0.17090959 0.35815217]]

 [[0.35944446 0.48089353 0.68866118 0.88047589 0.91823547 0.21682214]
  [0.56518887 0.86510256 0.50896896 0.91672295 0.92115761 0.08311249]
  [0.27771856 0.0093567  0.84234208 0.64717414 0.84138612 0.26473016]
  [0.39782075 0.55282148 0.16494046 0.36980809 0.14644176 0.56961841]
  [0.70373728 0.28847644 0.43328806 0.75610669 0.39609828 0.89603839]]]


In [ ]:

print(n[0::2, 1:4, 1::2]) # rows (2-5) and columns at an interval of 2, starting from 1 ##howwwwwww

[[[0.72063265 0.53737323 0.10590761]
  [0.18633234 0.21655035 0.32414101]
  [0.22232139 0.90259848 0.61306346]]

 [[0.86510256 0.91672295 0.08311249]
  [0.0093567  0.64717414 0.26473016]
  [0.55282148 0.36980809 0.56961841]]]


# 3.Modifying Data

### Modify single values

In [ ]:
#When you assign an array or its elements to a new variable,
#you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array.

n_copy = np.copy(n)

# check if values in the two arrays are the same before copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

n_copy[2, 4, :] = 0.005

# check if values in the two arrays are the same after copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

True
False


In [ ]:
n_copy

array([[[0.95715516, 0.14035078, 0.87008726, 0.47360805, 0.80091075,
         0.52047748],
        [0.67887953, 0.72063265, 0.58201979, 0.53737323, 0.75861562,
         0.10590761],
        [0.47360042, 0.18633234, 0.73691818, 0.21655035, 0.13521817,
         0.32414101],
        [0.14967487, 0.22232139, 0.38648898, 0.90259848, 0.44994999,
         0.61306346],
        [0.90234858, 0.09928035, 0.96980907, 0.65314004, 0.17090959,
         0.35815217]],

       [[0.75068614, 0.60783067, 0.32504723, 0.03842543, 0.63427406,
         0.95894927],
        [0.65279032, 0.63505887, 0.99529957, 0.58185033, 0.41436859,
         0.4746975 ],
        [0.6235101 , 0.33800761, 0.67475232, 0.31720174, 0.77834548,
         0.94957105],
        [0.66252687, 0.01357164, 0.6228461 , 0.67365963, 0.971945  ,
         0.87819347],
        [0.50962438, 0.05571469, 0.45115921, 0.01998767, 0.44171092,
         0.97958673]],

       [[0.35944446, 0.48089353, 0.68866118, 0.88047589, 0.91823547,
         0.216822

### Modify multiple values

In [ ]:
# check if values in the two arrays are the same before copy
print(f"Are the arrays the same before modification: {n_copy[2, 3] == n[2, 3]}")
print(f"Before modifying values: {n_copy[2, 3]}")

n_copy[2, 3] = 0.5

print(f"After modifying values: {n_copy[2, 3]}")

# check if values in the two arrays are the same after copy
print(f"Are the arrays the same after modification: {n_copy[2, 3] == n[2, 3]}")

In [ ]:
n_copy

# 4.Pivoting Data

### a. Reshaping Arrays
Array reshaping is an operation that changes the shape of an array whilst maintaining the same data in the array.

For instance, reshaping from (3, 4, 5) -> (2, 5, 6) or from (3, 4, 5) -> (6, 10). A reshape operation is valid, so long as the product of the new shape specified matches the product of the old shape.

In [ ]:
s = np.random.rand(3, 4, 5)
print(f"Original Shape: {s.shape}")

# s.size

print(s)

Original Shape: (3, 4, 5)
[[[0.96896177 0.32099724 0.22126269 0.1412639  0.09725993]
  [0.98404224 0.26034093 0.53702252 0.44792617 0.09956909]
  [0.35231166 0.46924917 0.84114013 0.90464774 0.03755938]
  [0.50831545 0.16684751 0.77905102 0.8649333  0.41139672]]

 [[0.13997259 0.03322239 0.98257496 0.37329075 0.42007537]
  [0.05058812 0.36549611 0.01662797 0.23074234 0.7649117 ]
  [0.94412352 0.74999925 0.33940382 0.48954894 0.33898512]
  [0.17949026 0.1709866  0.46345098 0.87457296 0.94411975]]

 [[0.60825287 0.59665541 0.78364425 0.5000263  0.05037006]
  [0.69909807 0.9923964  0.26726254 0.67909062 0.86428144]
  [0.75084425 0.96448977 0.55424244 0.2123905  0.22244322]
  [0.21874937 0.56957353 0.45210904 0.97023668 0.68054469]]]


In [ ]:
s.size

60

In [ ]:
s1 = s.reshape(2, 6, 5)
print(f"Reshaped from s: {s1.shape}")

print(s1)

Reshaped from s: (2, 6, 5)
[[[0.96896177 0.32099724 0.22126269 0.1412639  0.09725993]
  [0.98404224 0.26034093 0.53702252 0.44792617 0.09956909]
  [0.35231166 0.46924917 0.84114013 0.90464774 0.03755938]
  [0.50831545 0.16684751 0.77905102 0.8649333  0.41139672]
  [0.13997259 0.03322239 0.98257496 0.37329075 0.42007537]
  [0.05058812 0.36549611 0.01662797 0.23074234 0.7649117 ]]

 [[0.94412352 0.74999925 0.33940382 0.48954894 0.33898512]
  [0.17949026 0.1709866  0.46345098 0.87457296 0.94411975]
  [0.60825287 0.59665541 0.78364425 0.5000263  0.05037006]
  [0.69909807 0.9923964  0.26726254 0.67909062 0.86428144]
  [0.75084425 0.96448977 0.55424244 0.2123905  0.22244322]
  [0.21874937 0.56957353 0.45210904 0.97023668 0.68054469]]]


#### Reshaping to a different number of dimensions

In [ ]:
r = np.arange(120)

print(f"Original shape: {r.shape}")

print(r)

Original shape: (120,)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


In [ ]:
# (120,) -> (3, 4, 10)
r1 = r.reshape(3, 4, 10) # this can also be written as r.reshape((3, 4, 10))
print(f"Reshaped from r: {r1.shape}")

print(r1)

Reshaped from r: (3, 4, 10)
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]


In [ ]:
# (3, 4, 10) -> (6, 20)
r2 = r1.reshape(6, 20)
print(f"Reshaped from r1: {r2.shape}")

print(r2)

Reshaped from r1: (6, 20)
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]]


### b. Transposing Arrays
The transpose operation reverses the order of an array. It switches the rows to columns and vice versa. In a multi-dimensional array, the transpose operation moves the data from one axis to another in the order specified in the transpose method.

In [ ]:
x=np.arange(50).reshape((5,10))
print("Shape of the original array", x.shape)
print("Original array\n", x)

x1=np.transpose(x)
print("Shape of the transposed array", x1.shape)
print("Transposed array\n", x1)



Shape of the original array (5, 10)
Original array
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Shape of the transposed array (10, 5)
Transposed array
 [[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


In [ ]:
print(x.T)

[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


In [ ]:
w = np.arange(60).reshape((3, 4, 5))
# w

print("Shape of the Original array", w.shape)
print("Original array\n", w)


#### Transpose without specifying axes

In [ ]:
# Original Shape: 3,4,5

w1 = np.transpose(w)  # 0->2, 1->1, 2->0   (0,1,2)->(2,1,0)
print("Shape of the transposed array", w1.shape)
print("Transposed array\n", w1)

### c. Flattening Arrays
The flatten operation in Numpy collapses arrays of multiple dimensions into one dimension.


Different orders can be specified when flattening Numpy Arrays. See examples below.

In [ ]:
k = np.random.rand(5, 6)

k

array([[8.52955659e-02, 5.64183327e-02, 4.87837704e-01, 8.81004562e-01,
        9.76404387e-01, 6.17657916e-01],
       [5.42498775e-01, 8.54613580e-01, 7.43834545e-01, 4.78596326e-01,
        6.77081574e-01, 6.07045061e-01],
       [7.14696936e-01, 4.69497183e-01, 4.56014623e-01, 9.06418087e-01,
        1.37220420e-01, 2.29219323e-01],
       [8.81585399e-01, 9.04424976e-01, 6.45784599e-01, 3.24682972e-01,
        5.19711194e-01, 5.53568650e-05],
       [3.11860221e-01, 4.25451538e-01, 8.85337660e-01, 6.79879456e-01,
        4.56129772e-01, 4.83408617e-01]])

In [ ]:
k1 = k.flatten() # all rows are stacked on each other into a 1D array.
print(k1)

k1.shape

[8.52955659e-02 5.64183327e-02 4.87837704e-01 8.81004562e-01
 9.76404387e-01 6.17657916e-01 5.42498775e-01 8.54613580e-01
 7.43834545e-01 4.78596326e-01 6.77081574e-01 6.07045061e-01
 7.14696936e-01 4.69497183e-01 4.56014623e-01 9.06418087e-01
 1.37220420e-01 2.29219323e-01 8.81585399e-01 9.04424976e-01
 6.45784599e-01 3.24682972e-01 5.19711194e-01 5.53568650e-05
 3.11860221e-01 4.25451538e-01 8.85337660e-01 6.79879456e-01
 4.56129772e-01 4.83408617e-01]


(30,)

#### Flattening Arrays along the column

In [ ]:
k2= k.flatten('F') # forms a 1D array where elements in a column are listed before moving to the next column.

k2.shape

In [ ]:
k2

#### Flattening Arrays using Numpy Reshape


In [ ]:
k4= k.reshape(-1)

k4.shape

In [ ]:
k4

# Combining Data

## a.Concatenation
A concatenation operation joins a sequence of arrays along an *existing* axis. All arrays must either have the same shape (except in the concatenating dimension) or be empty.


In [ ]:
# Concatenating Numpy Arrays

array1 = np.random.randint(3, size = (3, 2, 2))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 2, 2))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

concatenated_array1 = np.concatenate((array1, array2), axis = 0)
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

concatenated_array2 = np.concatenate((array1, array2), axis = 1)
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

concatenated_array3 = np.concatenate((array1, array2), axis = 2)
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)

## b.Stacking
The stack operation joins a sequence of arrays along a *new* axis. The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis = 0 it will be the first dimension and if axis = -1 it will be the last dimension. All arrays need to be of the same size.  The stacked array has one more dimension than the input arrays.

In [ ]:
# Stacking 1-d Arrays

array1 = np.array([1, 2, 3])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([4, 5, 6])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")


stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 is \n", stacked_array1, " with dimensions ", stacked_array1.shape)

stacked_array2 = np.stack((array1, array2), axis = 1)
print("Stacked array 2 is \n", stacked_array2, " with dimensions ", stacked_array2.shape)

stacked_array3 = np.stack((array1, array2), axis = -1)
print("Stacked array 3 is \n", stacked_array3, " with dimensions ", stacked_array3.shape)

In [ ]:

# Stacking Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 has dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 has dimensions ", array2.shape, "\n")

stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 has dimensions", stacked_array1.shape, "\n")

stacked_array2 = np.stack((array1, array2), axis = 1)
print("Stacked array 2 has dimensions", stacked_array2.shape, "\n")

stacked_array3 = np.stack((array1, array2), axis = 2)
print("Stacked array 3 has dimensions", stacked_array3.shape, "\n")

stacked_array4 = np.stack((array1, array2), axis = -1)
print("Stacked array 4 has dimensions", stacked_array4.shape, "\n")

# Math Operations

In this section we will cover some commonly used mathematical operations
1. Broadcasting
1. Point-wise/element-wise operations
1. Reduction operations
1. Comparison operations
1. Vector/Matrix operations

In [ ]:
# Broadcasting b/w arrays of different dimensions
# Note: When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the arrays should have length 1 in that specific dimension

row_arr = np.random.rand(1,3)
print("A row array: \n", row_arr, " with dimensions ", row_arr.shape, "\n")
col_arr = np.random.rand(4,1)
print("A column array: \n", col_arr, " with dimensions ", col_arr.shape, "\n")

add_arr = row_arr + col_arr
print("row array + column array = ")
print(add_arr," with dimensions ", add_arr.shape, "\n")
mul_arr = row_arr * col_arr
print("row array * column array = ")
print(mul_arr," with dimensions ", mul_arr.shape, "\n")

### b. Element-wise operations

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print("A random array1 : \n", rand_arr_1, " with dimensions ", rand_arr_1.shape, "\n")
rand_arr_2 = np.random.rand(2,3)
print("A random array2 : \n", rand_arr_2, " with dimensions ", rand_arr_2.shape, "\n")
scalar = 5.0

# Addition with Scalars
new_arr_1 = rand_arr_1 + scalar
print("random array1 + 5.0 =")
print(new_arr_1, "\n")

# Multiplication with Scalars
new_arr_2 = rand_arr_1 * scalar
print("random array1 * 5.0 =")
print(new_arr_2, "\n")

# Elementwise Addition of Arrays
new_arr_3 = rand_arr_1 + rand_arr_2
print("random array1 + random array2 =")
print(new_arr_3, "\n")

# Elementwise Multiplication of Arrays aka Hadmard Product
new_arr_4 = rand_arr_1 * rand_arr_2
print("random array1 * random array2 =")
print(new_arr_4, "\n") # also equivalent to np.multiply(array1, array2)

# Absolute value
new_arr_5 = np.abs(-10*rand_arr_1)
print("abs (-10 * random array1) =")
print(new_arr_5, "\n")

# Square root value
new_arr_6 = np.sqrt(rand_arr_1)
print('sqrt(random array1) = \n', new_arr_6, "\n")

### c. Reduction

In [ ]:
rand_arr = np.random.rand(2,3)
print('random array: \n', rand_arr, "\n")

max_val = np.max(rand_arr)
print('Maximum value of array \n', max_val, "\n")
min_val = np.min(rand_arr)
print('Minimum value of array \n', min_val, "\n")

sum_val = np.sum(rand_arr)
print('Sum of array \n', sum_val, "\n")
max_idx = np.argmax(rand_arr, axis=0)
print('Maximum value\'s index of array along axis 0 \n', max_idx, "\n")
min_idx = np.argmin(rand_arr, axis=1)
print('Minimum value\'s index of array along axis 1 \n', min_idx, "\n")

mean_val = np.mean(rand_arr)
print('Mean value of array \n', mean_val, "\n")
std_val = np.std(rand_arr)
print('Standard deviation value of array \n', std_val, "\n")
norm_val = np.linalg.norm(rand_arr)
print('Norm value of array \n', norm_val, "\n")

### d. Comparision

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print('random array1: \n', rand_arr_1, '\n')
rand_arr_2 = np.random.rand(2,3)
print('random array2: \n', rand_arr_2, '\n')

# Element-wise Comparison Operations
greater_compare = rand_arr_1 > rand_arr_2
print('random array1 > random array2')
print(greater_compare, '\n')

less_compare = rand_arr_1 < rand_arr_2
print('random array1 < random array2')
print(less_compare, '\n')

not_equal_compare = rand_arr_1 != rand_arr_2
print('random array1 != random array2')
print(not_equal_compare, '\n')

# Combining reduction operations with boolean arrays
print("any values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(), "\n")

print("all values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).all(), "\n")

print("any values along first axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=0), "\n")

print("any values along second axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=1), "\n")

print("any values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).any(), "\n")

print("all values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).all(), "\n")

In [ ]:
rand_mat_1 = np.random.rand(4,2)
rand_mat_2 = np.random.rand(2,3)
print('Matrix1 \n', rand_mat_1, 'with dimension ', rand_mat_1.shape, '\n')
print('Matrix2 \n', rand_mat_2, 'with dimension ', rand_mat_2.shape, '\n')

# dot product
dot_mat = np.dot(rand_mat_1, rand_mat_2)
another_mat = rand_mat_1@rand_mat_2
print('Dot product of two matrices can be derived by using np.dot(mat1, mat2) \n', dot_mat)
print('Dot product of two matrices can also be derived by using mat1@mat2 \n', another_mat)
print('Dimensions of resulting product: \n', dot_mat.shape)

a = np.ones([9, 5, 7, 4])
b = np.ones([9, 5, 4, 3])
print('array1 \'s dimension ', a.shape, '\n')
print('array2 \'s dimension ', b.shape, '\n')

# matmul with multi-dimenstion arrays
c = np.matmul(a,b)
print('Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) \n')
print('Dimensions of resulting product: \n', c.shape)